# Telegram configuration
telegram:
  #App ID and Hash from my.telegram.org
  api_id: 2171111
  api_hash: "fd7acd07303760c52dcc0ed8b2f73086"
  # Bot token from @BotFather
  token: "1963945108:AAGwd4gDTg3QhfRpuN-flu4NDvGkvs60Yj4"

# Spamwatch credentials
spamwatch:
  token: abcd~1234ABCD

# Bot configuration
bot:
  # List of allowed chats ids.
  allowed_chats:
    - -1001263664495
    - -1001426113453
    - -1001536437727
    # The chat id where all the bugs and suggestions are sent after confirmation
  suggesion_chat: -1001263664495

  # Where the bot should check for the dispenser hook(s). In aurora is used to retrieve anonymous emails to use with AuroraStore.
  dispenser_urls:
    - http://auroraoss.com:8080
    - http://auroraoss.in:8080
